Blast4-archive ::= {
  request {
    ident "2.2.31+",
    body queue-search {
      program "blastn",
      service "megablast",
      queries bioseq-set {
        seq-set {
          seq {
            id {
              local str "Query_1"
            },
            descr {
              user {
                type str "CFastaReader",
                data {
                  {
                    label str "DefLine",
                    data str ">Oe6_s01884"
                  }
                }
              },
              title "Oe6_s01884"
            },
            inst {
              repr raw,
              mol na,
              length 547,
              seq-data ncbi2na '8E94E8D3F81EBAFBEEFEF9AA8EBAF49E3C328EFBE27E7B
EF8EBAEBAEEBE6DA79E79E3BEEBAEBEEBE38E38E06B77AC8FED1AFE788EFEB9BE9969E7BEF9EFB
EFBE79E79EFB8F8F7913D0CFA354E130CDFAD45295BA14BDDBCBEE040D36D762F6376ACAB76D8E
4C65627E92A42B4AFEFCAA50BBF89B95E0A39638B2DB5EF4DEAD76CF6F4EBF7FBCD4CF9C'H
            }
          }
        }
      },
      subject database "/home/ubuntu/nt_db/nt",
      algorithm-options {
        {
          name "EvalueThreshold",
          value cutoff e-value { 1, 10, 1 }
        },
        {
          name "MaskAtHash",
          value boolean TRUE
        },
        {
          name "DustFilteringLevel",
          value integer 20
        },
        {
          name "DustFilteringWindow",
          value integer 64
        },
        {
          name "DustFilteringLinker",
          value integer 1
        },
        {
          name "UngappedMode",
          value boolean FALSE
        },
        {
          name "HitlistSize",
          value integer 500
        },
        {
          name "EffectiveSearchSpace",
          value big-integer 80641033515378
        }
      },
      program-options {
        {
          name "LCaseMask",
          value query-mask {
            locations {
              packed-int {
                {
                  from 86,
                  to 159,
                  id local str "Query_1"
                },
                {
                  from 86,
                  to 159,
                  id local str "Query_1"
                },
                {
                  from 228,
                  to 271,
                  id local str "Query_1"
                },
                {
                  from 228,
                  to 271,
                  id local str "Query_1"
                }
              }
            },
            frame plus1
          }
        }
      }
    }
  },
  results {
    alignments {
    },
    masks {
      {
        locations {
          packed-int {
            {
              from 86,
              to 159,
              id local str "Query_1"
            },
            {
              from 228,
              to 271,
              id local str "Query_1"
            }
          }
        },
        frame plus1
      }
    },
    ka-blocks {
      {
        lambda { 133270576282382, 10, -14 },
        k { 620991117264207, 10, -15 },
        h { 112409184650115, 10, -14 },
        gapped FALSE
      },
      {
        lambda { 128, 10, -2 },
        k { 46, 10, -2 },
        h { 85, 10, -2 },
        gapped TRUE
      }
    },
    search-stats {
      "Effective search space: 80641033515378",
      "Effective search space used: 80641033515378",
      "Length adjustment: 34"
    }
  }
}
